version: '3'

services:
  web-ftp:
    image: dddmmm/web-ftp:0.10
#    image: cardonaje/monstaftp:latest
#    build: .
    volumes:
      - "./license:/var/www/mftp/license"
      - "./settings:/var/www/mftp/settings"
      - "./languages:/var/www/mftp/application/languages"
    ports:
    - "80:80"
#    networks:
#      - webgateway
#    deploy:
#      labels:
#        - "traefik.backend=mftp"
#        - "traefik.frontend.rule=Host:mftp.3rco.be"
#        - "traefik.port=80"
#        - "traefik.enable=true"
#        - "traefik.docker.network=webgateway"
#        - "traefik.default.protocol=http"
#        - "traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:max-age=15552000"


#networks:
#  webgateway:
#    external: true

#BUILD images
#   docker build -t dddmmm/web-ftp:0.10 .
#   docker images
#   docker push dddmmm/web-ftp:0.10